//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9B84AE_a2zworkoutEntities : DbContext
    {
        public DB_9B84AE_a2zworkoutEntities()
            : base("name=DB_9B84AE_a2zworkoutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_category> tb_category { get; set; }
        public DbSet<tb_classificationDetail> tb_classificationDetail { get; set; }
        public DbSet<tb_classificationFood> tb_classificationFood { get; set; }
        public DbSet<tb_cliente> tb_cliente { get; set; }
        public DbSet<tb_columnsFood> tb_columnsFood { get; set; }
        public DbSet<tb_detailFood> tb_detailFood { get; set; }
        public DbSet<tb_detailFoodColumn> tb_detailFoodColumn { get; set; }
        public DbSet<tb_exercise> tb_exercise { get; set; }
        public DbSet<tb_exerciseComment> tb_exerciseComment { get; set; }
        public DbSet<tb_exerciseImage> tb_exerciseImage { get; set; }
        public DbSet<tb_favoriteExercise> tb_favoriteExercise { get; set; }
        public DbSet<tb_favoriteFood> tb_favoriteFood { get; set; }
        public DbSet<tb_food> tb_food { get; set; }
        public DbSet<tb_foodtype> tb_foodtype { get; set; }
        public DbSet<tb_meal> tb_meal { get; set; }
        public DbSet<tb_measurementType> tb_measurementType { get; set; }
        public DbSet<tb_perfil> tb_perfil { get; set; }
        public DbSet<tb_sesion> tb_sesion { get; set; }
        public DbSet<tb_subCategory> tb_subCategory { get; set; }
        public DbSet<tb_userFood> tb_userFood { get; set; }
        public DbSet<tb_usuario> tb_usuario { get; set; }
        public DbSet<tb_usuarioPerfil> tb_usuarioPerfil { get; set; }
        public DbSet<tb_workoutLog> tb_workoutLog { get; set; }
    }
}
