//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detailFood
    {
        public tb_detailFood()
        {
            this.tb_classificationDetail = new HashSet<tb_classificationDetail>();
            this.tb_detailFoodColumn = new HashSet<tb_detailFoodColumn>();
        }
    
        public int id_detailFood { get; set; }
        public string descripcion { get; set; }
        public int id_measurementType { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_classificationDetail> tb_classificationDetail { get; set; }
        public virtual tb_measurementType tb_measurementType { get; set; }
        public virtual ICollection<tb_detailFoodColumn> tb_detailFoodColumn { get; set; }
    }
}
