//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_favoriteFood
    {
        public int id_favoriteFood { get; set; }
        public int id_user { get; set; }
        public int id_food { get; set; }
    
        public virtual tb_food tb_food { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
