//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_meal
    {
        public tb_meal()
        {
            this.tb_userFood = new HashSet<tb_userFood>();
        }
    
        public int id_meal { get; set; }
        public string description { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_userFood> tb_userFood { get; set; }
    }
}
