//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_measurementType
    {
        public tb_measurementType()
        {
            this.tb_detailFood = new HashSet<tb_detailFood>();
        }
    
        public int id_measurementType { get; set; }
        public string unit { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_detailFood> tb_detailFood { get; set; }
    }
}
