//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_perfil
    {
        public tb_perfil()
        {
            this.tb_usuarioPerfil = new HashSet<tb_usuarioPerfil>();
        }
    
        public int id_perfil { get; set; }
        public string perfil { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_usuarioPerfil> tb_usuarioPerfil { get; set; }
    }
}
