//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.API.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_workoutLog
    {
        public int id_workoutLog { get; set; }
        public int id_user { get; set; }
        public int id_exercise { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<System.DateTime> reps { get; set; }
    
        public virtual tb_exercise tb_exercise { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
