//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_activityType
    {
        public tb_activityType()
        {
            this.tb_client = new HashSet<tb_client>();
        }
    
        public int id_activityType { get; set; }
        public string description { get; set; }
        public double value { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_client> tb_client { get; set; }
    }
}
