//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public tb_cliente()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string tipoDocumento { get; set; }
        public Nullable<int> documento { get; set; }
        public string telefono { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
