//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_client
    {
        public tb_client()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public int id_client { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public Nullable<int> currentWeight { get; set; }
        public Nullable<int> goalWeight { get; set; }
        public Nullable<int> height { get; set; }
        public System.DateTime birthDate { get; set; }
        public int id_Sexo { get; set; }
        public int id_activityType { get; set; }
        public int id_measurementUnits { get; set; }
        public int activo { get; set; }
    
        public virtual tb_activityType tb_activityType { get; set; }
        public virtual tb_measurementUnits tb_measurementUnits { get; set; }
        public virtual tb_sexo tb_sexo { get; set; }
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
