//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_classificationDetail
    {
        public int id_classificationDetail { get; set; }
        public int id_classificationFood { get; set; }
        public int id_detailFood { get; set; }
    
        public virtual tb_classificationFood tb_classificationFood { get; set; }
        public virtual tb_detailFood tb_detailFood { get; set; }
    }
}
