//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_columnsFood
    {
        public tb_columnsFood()
        {
            this.tb_detailFoodColumn = new HashSet<tb_detailFoodColumn>();
        }
    
        public int id_columnsfood { get; set; }
        public string descripcion { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_detailFoodColumn> tb_detailFoodColumn { get; set; }
    }
}
