//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public tb_cliente()
        {
            this.tb_usuario = new HashSet<tb_usuario>();
        }
    
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string tipoDocumento { get; set; }
        public Nullable<int> documento { get; set; }
        public string telefono { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_usuario> tb_usuario { get; set; }
    }
}
