//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detailFood
    {
        public tb_detailFood()
        {
            this.tb_classificationDetail = new HashSet<tb_classificationDetail>();
            this.tb_detailFoodColumn = new HashSet<tb_detailFoodColumn>();
        }
    
        public int id_detailFood { get; set; }
        public string descripcion { get; set; }
        public int id_measurementType { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_classificationDetail> tb_classificationDetail { get; set; }
        public virtual tb_measurementType tb_measurementType { get; set; }
        public virtual ICollection<tb_detailFoodColumn> tb_detailFoodColumn { get; set; }
    }
}
