//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detailFoodColumn
    {
        public int id_detailFoodColumn { get; set; }
        public int id_detailFood { get; set; }
        public int id_columnsfood { get; set; }
        public Nullable<double> foodValue { get; set; }
        public int activo { get; set; }
    
        public virtual tb_columnsFood tb_columnsFood { get; set; }
        public virtual tb_detailFood tb_detailFood { get; set; }
    }
}
