//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_detailFoodColumn
    {
        public int id_detailFoodColumn { get; set; }
        public int id_detailFood { get; set; }
        public int id_columnsfood { get; set; }
        public Nullable<double> foodValue { get; set; }
        public int activo { get; set; }
    
        public virtual tb_columnsFood tb_columnsFood { get; set; }
        public virtual tb_detailFood tb_detailFood { get; set; }
    }
}
