//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_measurementType
    {
        public tb_measurementType()
        {
            this.tb_detailFood = new HashSet<tb_detailFood>();
        }
    
        public int id_measurementType { get; set; }
        public string unit { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_detailFood> tb_detailFood { get; set; }
    }
}
