//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_meal
    {
        public tb_meal()
        {
            this.tb_userFood = new HashSet<tb_userFood>();
        }
    
        public int id_meal { get; set; }
        public string description { get; set; }
        public int activo { get; set; }
    
        public virtual ICollection<tb_userFood> tb_userFood { get; set; }
    }
}
