//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_subCategory
    {
        public tb_subCategory()
        {
            this.tb_exercise = new HashSet<tb_exercise>();
        }
    
        public int id_subCategory { get; set; }
        public string name { get; set; }
        public int id_category { get; set; }
        public int activo { get; set; }
    
        public virtual tb_category tb_category { get; set; }
        public virtual ICollection<tb_exercise> tb_exercise { get; set; }
    }
}
