//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sesion
    {
        public int id_sesion { get; set; }
        public string sesion { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaUlOper { get; set; }
        public int activo { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
