//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarioPerfil
    {
        public int id_usuarioPerfil { get; set; }
        public int id_usuario { get; set; }
        public int id_perfil { get; set; }
    
        public virtual tb_perfil tb_perfil { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
