//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_water
    {
        public int id_water { get; set; }
        public int cups { get; set; }
        public System.DateTime date { get; set; }
        public int id_usuario { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
