//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FoodDetail
    {
        public int FoodID { get; set; }
        public int FoodReference { get; set; }
        public Nullable<int> NDB { get; set; }
        public string ValGroup { get; set; }
        public string ValName { get; set; }
        public string ValType { get; set; }
        public Nullable<double> Val { get; set; }
        public string UnitType { get; set; }
    }
}
