//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieCounter.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FoodDetail
    {
        public int FoodID { get; set; }
        public int FoodReference { get; set; }
        public Nullable<int> NDB { get; set; }
        public string ValGroup { get; set; }
        public string ValName { get; set; }
        public string ValType { get; set; }
        public Nullable<double> Val { get; set; }
        public string UnitType { get; set; }
    }
}
